default_connection_name = "myconnection"
[connections]
[connections.myconnection]
warehouse = "COMPUTE_WH"
role = ${{ secrets.DEV_ROLE }}
database = "DEMO_DB"
schema = "DEMO"
account = "xq88480.ap-southeast-1"
user = "snow"
password = "#definePASS2"
