default_connection_name = "myconnection"
[connections]
[connections.myconnection]
warehouse = "COMPUTE_WH"
role = ${ROLE}
database = "DEMO_DB"
schema = "DEMO"
account = ${ACCOUNT}
user = ${USER}
password = ${PASSWORD}
