create or alter TABLE {{environment}}_INGESTION_DB.INOVA_BASE.DIMAGE (
	AGESK NUMBER(38,0) NOT NULL,
	AGERANGE VARCHAR(50),
	BASECREATEDDATE TIMESTAMP_NTZ(9),
	BASEUPDATEDDATE TIMESTAMP_NTZ(9),
	BASEDELETEDFLAG NUMBER(38,0)
);