name: Deploy data pipeline
on:
  push:
    branches:
    - dev
    - qa
    - prod

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to (dev, qa, prod)"
        required: false
        default: ""
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: "demo_db.demo.repo"
      SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Environment variables
        run: |
          echo "ROLE=${{ secrets.DEV_ROLE }}" >> $GITHUB_ENV
      - name: Determine branch name
        id: set-branch
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ -z "${{ github.event.inputs.environment }}" ]; then
              echo "Error: 'environment' input is required for manual runs."
              exit 1
            fi
            BRANCH_NAME="${{ github.event.inputs.environment }}"
          else
            BRANCH_NAME="${{ github.ref_name }}"
          fi
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Install snowflake-cli
        uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          default-config-file-path: ".snowflake/${{ github.ref_name }}/config.toml"

      - name: Fetch repository changes
        run: snow git fetch "${REPO_NAME}"

      - name: Deploy data pipeline
        run: |
          if [ "${BRANCH_NAME}" == "main" ]; then
            RETENTION_TIME=1
          else
            RETENTION_TIME=0
          fi
          snow git execute \
            "@${REPO_NAME}/branches/${BRANCH_NAME}/0[3456789]-*" \
            -D "environment='${BRANCH_NAME}'" \
            -D "retention_time=${RETENTION_TIME}"